'''
Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
find the sum of the even-valued terms.
'''

def fib_seq(number):
    num_list = [number, number + number]
    sum = 0
    
    while num_list[-1] < 4000000:
        num_list.append(num_list[-1] + num_list[-2]) 
    
    for num in num_list:
        if num % 2 == 0:
            sum += num
            
            
    return sum      

print fib_seq(1)
    
